version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: biblioteca-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-senha123}
      MONGO_INITDB_DATABASE: biblioteca
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
